- cosmos/poc/README.md
> Update cyberd/cosmos README

- cosmos/poc/commands/getlinks.go
- cosmos/poc/cyberdcli/main.go
- cosmos/poc/go.sum
> Cosmos POC: Clean up CLI

- .circleci/config.yml
- cosmos/poc/config.toml
> Add Circle CI build job

- cosmos/poc/app/storage/inmemory.go
- cosmos/poc/scripts/reset_earth_docker.sh
Fix search on non existing cid
> Fix search on non existing cid

- cosmos/poc/http/util/util.go
- cosmos/poc/proxy/core/context.go
- cosmos/poc/proxy/core/get.go
- cosmos/poc/proxy/core/tx.go
Proxy service. Search request with spaces fails
> Proxy service. Search request with spaces fails

- cosmos/poc/app/rpc.go
- cosmos/poc/cyberd/rpc/search.go
- cosmos/poc/http/util/util.go
- cosmos/poc/proxy/client/start.go
- cosmos/poc/proxy/core/get.go
- cosmos/poc/proxy/core/tx.go
Proxy service. Add search pagination
> Proxy service. Add search pagination

- cosmos/poc/app/app.go
- cosmos/poc/app/genesis.go
- cosmos/poc/app/msgs.go
- cosmos/poc/app/storage/acc.go
- cosmos/poc/app/storage/inmemory.go
- cosmos/poc/claim/common/verifier.go
- cosmos/poc/cyberd/init.go
- cosmos/poc/cyberd/main.go
- cosmos/poc/go.mod
- cosmos/poc/go.sum
- cosmos/poc/proxy/core/tx.go
Update cosmos-sdk version to 0.26.1
Tested with current version of cyb
> Update cosmos-sdk version to 0.26.1

- cosmos/poc/app/prefix.go
- cosmos/poc/claim/context/ctx.go
- cosmos/poc/cyberd/main.go
- cosmos/poc/cyberdcli/main.go
- cosmos/poc/proxy/core/context.go
Remove 'cosmosaccaddr' prefix from cyberd address
> Remove 'cosmosaccaddr' prefix from cyberd address

- app/genesis.go
- app/params.go
- cyberd/init/testnet.go
Small fixes for validators joining
> Small fixes for validators joining

- app/app.go
- app/export.go
- app/genesis.go
- app/params.go
- app/rank/calculate_gpu_nop.go
- app/storage/main.go
- cyberdcli/main.go
- testnet/config.toml
- x/mint/abci.go
- x/mint/minter.go
- x/mint/params.go
--add 100% first year inflation
>  #1 Build basic economic model

- app/app.go
- app/storage/main.go
- x/bandwidth/end_blocker.go
- x/bandwidth/handler.go
- x/bandwidth/params.go
- x/bandwidth/types/acc_bandwidth.go
- x/bandwidth/types/handler.go
Add bandwidth by stake. Price adjustment
> [DON'T MERGE] Add bandwidth by stake. Part 2.

- app/app.go
- daemon/main.go
- docs/rank.md
- store/main.go
- util/utils.go
- x/bank/index.go
- x/link/keeper/link_index.go
- x/rank/calculate.go
- x/rank/calculate_cpu.go
- x/rank/calculate_gpu.go
- x/rank/calculate_gpu_nop.go
- x/rank/context.go
- x/rank/params.go
- x/rank/state.go
> Parallel rank calculation

- app/app.go
- client/flags.go
- docs/rank.md
- merkle/tree.go
- merkle/tree_test.go
- merkle/util.go
- store/main.go
- wiki/wiki.go
- x/link/keeper/cid.go
- x/link/keeper/link_index.go
- x/rank/calculate.go
- x/rank/context.go
- x/rank/rank.go
- x/rank/state.go
> Rank merkle proofs

- cli/commands/importprivate.go
- cli/main.go
- go.mod
Cli: Add possibility to restore acc from priv keys
> Cli: Add possibility to restore acc from priv keys

- docs/run_validator.md
> Important fixes in validators manual

- app/app.go
- app/export.go
- util/file.go
- x/link/genesis.go
- x/link/handler.go
- x/link/keeper/cid.go
- x/link/keeper/link.go
- x/link/keeper/link_index.go
- x/link/types/link.go
> Links exporter

- Dockerfile
- start_script.sh
> WIP: CI Cyberd docker image building. Include genesis file

- .circleci/config.yml
- Dockerfile
- cli/main.go
- docs/run_validator.md
- go.mod
- go.sum
- start_script.sh
Add cyberd rest light-client to docker image
> Add cyberd rest light-client to docker image

- start_script.sh
Rest server blocks cli keystore file
> Rest server blocks cli keystore file

- daemon/rpc/routes.go
- daemon/rpc/validators.go
Add staking/validators endpoint to node RPC
> Add staking/validators endpoint to node RPC

- Dockerfile
- README.md
- app/rpc.go
- client/http_client.go
- client/spec.go
- x/link/keeper/link_index.go
> Client submit only new links flag

- app/rpc.go
- store/main.go
- x/bank/index.go
- x/link/handler.go
- x/link/keeper/link_index.go
- x/rank/rank.go
- x/rank/state.go
Do not calculate rank, if there is no new links on last window.
> Do not calculate rank, if there is no new links on last window.

- app/app.go
- store/main.go
- x/rank/rank.go
- x/rank/state.go
Consensus failure after node restart
> Consensus failure after node restart

- x/link/keeper/cid.go
- x/link/keeper/link_index.go
- x/link/types/cid.go
- x/rank/index.go
- x/rank/index_types.go
- x/rank/rank.go
- x/rank/state.go
Refactoring  of search index. Fix links export
> Refactoring  of search index. Fix links export

- .circleci/config.yml
- README.md
- app/app_test.go
- cli/commands/keys/importprivate_test.go
- cli/commands/linktx_test.go
- client/httpclient_test.go
- daemon/cmd/testnet_test.go
- daemon/rpc/account_test.go
- store/storage_test.go
- types/acc_test.go
- types/coin/coins_test.go
- util/io_test.go
- x/bandwidth/abci_test.go
- x/bandwidth/types/accbandwidth_test.go
- x/bank/index_test.go
- x/debug/abci_test.go
- x/link/genesis_test.go
- x/link/keeper/cid_test.go
- x/link/types/cid_test.go
- x/mint/minter_test.go
- x/rank/rank_test.go
Add goveralls support for test coverage
> Add goveralls support for test coverage

- docs/get_CYB.md
> Change get-cyb description

- docs/cyberd.md
Several lines somehow disappeared during editing
> Fixes fatal mistake in distribution

- app/rpc.go
- daemon/main.go
- daemon/rpc/rank.go
- daemon/rpc/routes.go
- daemon/rpc/search.go
- merkle/node.go
- merkle/proof.go
- merkle/subtree.go
- x/rank/index.go
- x/rank/index_types.go
- x/rank/params.go
- x/rank/state.go
> 309 rank proof

- app/app.go
- x/link/keeper/link.go
- x/link/keeper/link_index.go
Added proofs for links, merkle root of links added to abci commit and app hash
reference to #299
> Merkle tree for links

- docs/Account setup with ledger.md
#391 guide to connect Ledger account to cyberd
> add Ledger support guide 

- app/app.go
- app/options.go
- daemon/main.go
- x/bandwidth/genesis.go
- x/bandwidth/internal/keeper/params.go
- x/bandwidth/internal/types/genesis.go
- x/bandwidth/internal/types/params.go
- x/rank/exported/exported.go
- x/rank/internal/keeper/invariants.go
- x/rank/internal/keeper/state.go
- x/rank/module.go
Update bw parameters
Move rank index check error from EndBlocker to invariant
> Improvements

- Dockerfile
- Makefile
Added makefile and upgraded Dockerfile to build with
Upgraded go version in Dockefile to 1.13
> Added Makefile, updated Dockerfile for

- x/rank/internal/keeper/calculate_cpu.go
- x/rank/internal/keeper/calculate_gpu.go
Cleaned CPU code, add workers for data preparation for GPU
references #400
> Refactoring of data preparation for GPU, added workers

- x/bandwidth/genesis.go
- x/bandwidth/internal/keeper/params.go
- x/bandwidth/internal/types/genesis.go
- x/bandwidth/internal/types/params.go
- x/bandwidth/meter.go
Refactoring
references #377 #386
> Band refactoring

- Dockerfile
- Makefile
- x/rank/cuda/Makefile
Added makefile for rank,
Added tag CUDA for daemon build
Updated Dockerfile with rank makefile
> Added makefile for rank, added tag CUDA for daemon build

- app/app.go
- x/bandwidth/internal/types/acc_bandwidth.go
- x/bandwidth/internal/types/meter.go
- x/bandwidth/meter.go
References #371 
Added indexing of used for linking account bandwidth
> Added stat for used for linking band

- client/http_client.go
- client/spec.go
Refactored client after app refactoring
Fixed tx building and options to
> Client upgrade

- docs/Validator launch with Tendermint KMS + Ledger.md
Work in progress, last part of doc is unfinished yet
> add Tendermint KMS  with Leger validator setup

- docs/run_validator.md
Fixed Nvidia GPU testing to 
`docker run --gpus all nvidia/cuda:10.0-base nvidia-smi`
Add parameter --gpus all to run container command.
Removed some tailing spaces and empty lines.
> run_validator_fixes

- app/rpc.go
- cmd/cyberd/rpc/routes.go
- cmd/cyberd/rpc/top.go
- x/rank/exported/exported.go
- x/rank/internal/keeper/state.go
- x/rank/internal/types/index.go
- x/rank/internal/types/index_types.go
- x/rank/internal/types/rank.go
> Implemented top cids endpoint and top processing

- .gitignore
- app/rpc.go
- cmd/cyberd/rpc/network.go
- x/bandwidth/internal/types/acc_bandwidth.go
- x/bandwidth/internal/types/meter.go
- x/bandwidth/meter.go
- x/rank/cuda/Makefile
> Added used overall karma generated by agents

- x/rank/internal/types/rank.go
> Added skipping of NaN objects during sorting

- x/bank/exported/exported.go
- x/bank/internal/keeper/index.go
- x/rank/internal/keeper/state.go
- x/rank/internal/types/expected_keepers.go
> Fixed triggering of rank calculation by modules

- app/app.go
- x/bandwidth/internal/types/meter.go
- x/bandwidth/meter.go
> Fixed calculation of overall karma

- x/rank/cuda/rank.cu
- x/rank/internal/keeper/calculate_cpu.go
> Fixed NaN in weights calculation in CPU/GPU

- Dockerfile
> Add cosmwasm docker build stage

- x/link/internal/types/codec.go
> Rename cyberlink msg

- app/ante.go
- app/app.go
> Add custom ante handler with applied infinity gas meter

- x/link/internal/keeper/keeper.go
> Fix iteration over links storage

- x/link/handler.go
> Fix event manager for NewLinksHangler

- cmd/cyberdcli/commands/keys/importprivate.go
> Fixed ethereum private key import

- app/app.go
- x/bandwidth/exported/exported.go
- x/link/handler.go
- x/link/internal/types/events.go
- x/link/module.go
> Add used karma to cyberlinks events

- app/rpc.go
- cmd/cyberd/rpc/load.go
- cmd/cyberd/rpc/routes.go
- x/bandwidth/internal/types/meter.go
- x/bandwidth/meter.go
> Add RPC endpoint for network load

- go.mod
- go.sum
> Upgrade sdk and tm versions due to security issue

- docs/port_forwarding_guide.md
- docs/supported_gpu_list.md
According to [397](https://github.com/cybercongress/congress/issues/397)
and [398](https://github.com/cybercongress/congress/issues/398)
issues from congress repo.
> docs_fixes

- docs/run_validator.md
- docs/ultimate-commands-guide.md
Fixed some important stuff required to be set for correct upgrade.
> Master docs update

- app/rpc.go
- cmd/cyberd/rpc/rank.go
- x/rank/exported/exported.go
- x/rank/internal/keeper/calculate_cpu.go
- x/rank/internal/keeper/keeper.go
- x/rank/internal/types/index.go
- x/rank/internal/types/index_types.go
- x/rank/internal/types/rank.go
> Uints rank's values

- x/rank/cuda/rank.cu
Reference to #132 
Fix of critical bug related to non-freed allocated memory which follow to memory leak
> Fixed freeing of allocated memory

- cmd/cyberd/rpc/rank.go
This PR fixed issue with passing missed context to rpc endpoint
> Fixed call of rank rpc endpoint

- x/bank/internal/keeper/index.go
> Skip indexing of not existed account

- README.md
Fixed endpoint to pull "Blockchain" stats to readme.md
> fixed_readme_blockhain_stats

- docs/run_validator.md
Updated node requirements (disk size)
Fixed some naming typo's
> some typo fixes, node rquirements fixes

- docs/supported_gpu_list.md
> new supported and tested GPUs

- docs/run_validator.md
> edited text

- docs/run_validator.md
edited for typos/grammar 9 feb 2022
> Edited for typos and grammar

- README.md
- docs/multisig_guide.md
- docs/run_validator.md
- docs/ultimate-commands-guide.md
- add documentation links to readme
- one style of bash commands
- some fixes
> Update Readme and Documentation

- .github/tests.yml
This PR uses @mvdan's excellent CI test suite to run tests on two go language versions and three operating systems so 
that we can be more assured of each PR's validitiy.
> run tests in github actions
